quiet: False
disable-version-string: True
with-expecter: False

# NOTE: on external packages set this value to "{{.PackagePath}}"
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName}}_test.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_test"

packages:
  github.com/omareloui/odinls/internal/application/core/product:
    config:
    interfaces:
      ProductService:
      ProductRepository:
  github.com/omareloui/odinls/internal/application/core/client:
    interfaces:
      ClientService:
      ClientRepository:
  github.com/omareloui/odinls/internal/application/core/counter:
    interfaces:
      CounterService:
      CounterRepository:
  github.com/omareloui/odinls/internal/application/core/order:
    interfaces:
      OrderService:
      OrderRepository:
