// Code generated by mockery. DO NOT EDIT.

package material_mock

import (
	jwtadapter "github.com/omareloui/odinls/internal/adapters/jwt"
	material "github.com/omareloui/odinls/internal/application/core/material"

	mock "github.com/stretchr/testify/mock"
)

// MockMaterialService is an autogenerated mock type for the MaterialService type
type MockMaterialService struct {
	mock.Mock
}

// CreateMaterial provides a mock function with given fields: claims, mat, opts
func (_m *MockMaterialService) CreateMaterial(claims *jwtadapter.AccessClaims, mat *material.Material, opts ...material.RetrieveOptsFunc) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims, mat)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateMaterial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.AccessClaims, *material.Material, ...material.RetrieveOptsFunc) error); ok {
		r0 = rf(claims, mat, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMaterialByID provides a mock function with given fields: claims, id, opts
func (_m *MockMaterialService) GetMaterialByID(claims *jwtadapter.AccessClaims, id string, opts ...material.RetrieveOptsFunc) (*material.Material, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMaterialByID")
	}

	var r0 *material.Material
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.AccessClaims, string, ...material.RetrieveOptsFunc) (*material.Material, error)); ok {
		return rf(claims, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(*jwtadapter.AccessClaims, string, ...material.RetrieveOptsFunc) *material.Material); ok {
		r0 = rf(claims, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*material.Material)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwtadapter.AccessClaims, string, ...material.RetrieveOptsFunc) error); ok {
		r1 = rf(claims, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMaterials provides a mock function with given fields: claims, opts
func (_m *MockMaterialService) GetMaterials(claims *jwtadapter.AccessClaims, opts ...material.RetrieveOptsFunc) ([]material.Material, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMaterials")
	}

	var r0 []material.Material
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.AccessClaims, ...material.RetrieveOptsFunc) ([]material.Material, error)); ok {
		return rf(claims, opts...)
	}
	if rf, ok := ret.Get(0).(func(*jwtadapter.AccessClaims, ...material.RetrieveOptsFunc) []material.Material); ok {
		r0 = rf(claims, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]material.Material)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwtadapter.AccessClaims, ...material.RetrieveOptsFunc) error); ok {
		r1 = rf(claims, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMaterialByID provides a mock function with given fields: claims, id, mat, opts
func (_m *MockMaterialService) UpdateMaterialByID(claims *jwtadapter.AccessClaims, id string, mat *material.Material, opts ...material.RetrieveOptsFunc) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims, id, mat)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMaterialByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.AccessClaims, string, *material.Material, ...material.RetrieveOptsFunc) error); ok {
		r0 = rf(claims, id, mat, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMaterialService creates a new instance of MockMaterialService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaterialService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaterialService {
	mock := &MockMaterialService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
