// Code generated by mockery. DO NOT EDIT.

package client_test

import (
	jwtadapter "github.com/omareloui/odinls/internal/adapters/jwt"
	client "github.com/omareloui/odinls/internal/application/core/client"

	mock "github.com/stretchr/testify/mock"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

// CreateClient provides a mock function with given fields: claims, _a1, opts
func (_m *MockClientService) CreateClient(claims *jwtadapter.JwtAccessClaims, _a1 *client.Client, opts ...client.RetrieveOptsFunc) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, *client.Client, ...client.RetrieveOptsFunc) error); ok {
		r0 = rf(claims, _a1, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClientByID provides a mock function with given fields: claims, id, opts
func (_m *MockClientService) GetClientByID(claims *jwtadapter.JwtAccessClaims, id string, opts ...client.RetrieveOptsFunc) (*client.Client, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetClientByID")
	}

	var r0 *client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, string, ...client.RetrieveOptsFunc) (*client.Client, error)); ok {
		return rf(claims, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, string, ...client.RetrieveOptsFunc) *client.Client); ok {
		r0 = rf(claims, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwtadapter.JwtAccessClaims, string, ...client.RetrieveOptsFunc) error); ok {
		r1 = rf(claims, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClients provides a mock function with given fields: claims, opts
func (_m *MockClientService) GetClients(claims *jwtadapter.JwtAccessClaims, opts ...client.RetrieveOptsFunc) ([]client.Client, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetClients")
	}

	var r0 []client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, ...client.RetrieveOptsFunc) ([]client.Client, error)); ok {
		return rf(claims, opts...)
	}
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, ...client.RetrieveOptsFunc) []client.Client); ok {
		r0 = rf(claims, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwtadapter.JwtAccessClaims, ...client.RetrieveOptsFunc) error); ok {
		r1 = rf(claims, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrentMerchantClients provides a mock function with given fields: claims, opts
func (_m *MockClientService) GetCurrentMerchantClients(claims *jwtadapter.JwtAccessClaims, opts ...client.RetrieveOptsFunc) ([]client.Client, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentMerchantClients")
	}

	var r0 []client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, ...client.RetrieveOptsFunc) ([]client.Client, error)); ok {
		return rf(claims, opts...)
	}
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, ...client.RetrieveOptsFunc) []client.Client); ok {
		r0 = rf(claims, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwtadapter.JwtAccessClaims, ...client.RetrieveOptsFunc) error); ok {
		r1 = rf(claims, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClientByID provides a mock function with given fields: claims, id, _a2, opts
func (_m *MockClientService) UpdateClientByID(claims *jwtadapter.JwtAccessClaims, id string, _a2 *client.Client, opts ...client.RetrieveOptsFunc) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, claims, id, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClientByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwtadapter.JwtAccessClaims, string, *client.Client, ...client.RetrieveOptsFunc) error); ok {
		r0 = rf(claims, id, _a2, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
